name: firestore_size
description: A tiny package to calculate the approximate size (in bytes) of a Firestore document.

repository: https://github.com/BirjuVachhani/firestore_size
homepage: https://github.com/BirjuVachhani/firestore_size
issue_tracker: https://github.com/BirjuVachhani/firestore_size/issues

version: 1.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ">=5.0.0 <6.0.0"
  intl: ">=0.18.0 <0.30.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
  fake_cloud_firestore: ^3.1.0

scripts: scripts.yaml
