name: Build

on:
  push:
    paths:
      - '**.dart'
      - '**.yaml'
      - '**.yml'
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: flutter pub get
      - name: Code Formatting
        run: dart format --set-exit-if-changed .
      - name: Analyze
        run: flutter analyze
      - name: Check Publish Warnings
        run: dart pub publish --dry-run